export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
  SET_FILTER_QUERY: "SET_FILTER_QUERY",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
